### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by stwars7** [ZindGH/masters#6]
Hi there! Thx for sharing ur work! I have some questions about script in "main.py". There is 2 problems with "peaks" and "base", cause they are not defined, so could u help me and explain what does these two parameters mean? In the code there are 117 and 163 lines. Thank u!

**Comment by ZindGH** [comment]
Well, i didn't find corresponding lines for peaks. However, peaks variable usually contains numpy array or python list of R peak indexes found (ECG contains P-Q-R-S-T-U points, so R one has the most amplitude).

Base: `Processing.scatter_beautiful(base, ...)`. In processing module I have `bwr` for baseline wavelet removal. With help of wavelet decomposition it looks for trend (very low frequency component) and deletes it from original signal. So, commented function in main.py prints this wave. 

Thanks for interest.
